name: pytest with pycodestyle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run:  pip install -r ./weight_entry/requirements.txt
    - name: Test with pytest
      run:
        pytest -v --pycodestyle --cache-clear ./weight_entry
